Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.define "OpenVPN" do |vpn|
     vpn.vm.hostname = "openvpn"
     vpn.vm.network "private_network", ip: "192.168.77.200"
     vpn.vm.provision :ansible do |ansible|
       ansible.limit = "all"
       ansible.inventory_path = "test/hosts/vagrant"
       ansible.playbook = "main.yml"
    end
  end
end
