sudo: required

language: bash

services:
  - docker
   
script:
   - docker build -t sifungurx/openvpn -f tests/Dockerfile .
   - docker create -v /etc/openvpn/clients --name client_datacontainer alpine
   - docker create -v /etc/openvpn/certs --volumes-from client_datacontainer --name ovpn_datacontainer alpine
   - docker run -it --volumes-from ovpn_datacontainer --name openvpn_test --privileged --cap-add=NET_ADMIN sifungurx/openvpn setup
   - docker start openvpn_test
   
   
   - docker ps | grep sifungurx/openvpn
   - docker images | grep sifungurx/openvpn
   
   - docker exec -it openvpn_test cd /usr/local/bin/ && ls setup && ls ovpn && addclinent

   - docker exec -it openvpn_test /etc/init.d/openvpn status || true
   
   
   #- docker exec -it openvpn_test addclient test1
