---

- name: Check for existing client config
  stat:
    path: "{{ easy_rsa_client_dir }}/{{ client }}/{{ client }}.tar.gz"
  register: check_clients_config
  tags:
    - addclient

- name: Create client folder
  file:
    path: "{{ easy_rsa_client_dir }}/{{ client }}"
    state: directory
    mode: 0700
  tags:
    - addclient

- name: Generate client key and certificate request
  command: >
    {{ easy_rsa_dir }}/easyrsa
    --pki-dir={{ easy_rsa_cert_dir }}
    gen-req {{ client }} nopass
  when: not check_clients_config.stat.exists
  environment:
    EASYRSA_BATCH: "1"
  tags:
    - addclient

- name: Sign client certificate
  command: >
    {{ easy_rsa_dir }}/easyrsa
    --pki-dir={{ easy_rsa_cert_dir }}
    sign-req client {{ client }}
  when: not check_clients_config.stat.exists
  environment:
    EASYRSA_BATCH: "1"
  tags:
    - addclient

- name: Generate client configuration
  template:
    src: templates/client.conf.j2
    dest: "{{ easy_rsa_client_dir }}/{{ client }}/client.conf"
  when: not check_clients_config.stat.exists
  tags:
    - addclient

- name: Collect client certificates and keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ easy_rsa_client_dir }}/{{ client }}/"
    remote_src: true
  loop:
    - { src: "{{ easy_rsa_cert_dir }}/issued/{{ client }}.crt" }
    - { src: "{{ easy_rsa_cert_dir }}/private/{{ client }}.key" }
    - { src: "{{ easy_rsa_cert_dir }}/ca.crt" }
  when: not check_clients_config.stat.exists
  tags:
    - addclient

- name: Collect tls-auth key
  copy:
    src: "{{ easy_rsa_cert_dir }}/ta.key"
    dest: "{{ easy_rsa_client_dir }}/{{ client }}/"
    remote_src: true
  when:
    - easy_rsa_keys.tls_auth == True
    - not check_clients_config.stat.exists
  tags:
    - addclient

- name: Archive client configuration and certificates
  archive:
    path: "{{ easy_rsa_client_dir }}/{{ client }}"
    dest: "{{ easy_rsa_client_dir }}/{{ client }}/{{ client }}.tar.gz"
  when: not check_clients_config.stat.exists
  tags:
    - addclient
