---

- name: Include variables
  vars: 
  include_vars:
    file: defaults/main.yml

- name: Installere openvpn til sidste version
  apt:
    pkg: openvpn
    state: latest
    update_cache: yes
  tags:
    - install
    - docker

- name: Create folder
  file:
    path: "{{ openvpn_dir }}/{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - certs
    - clients
    - configs
  tags:
    - install

- copy:
    src: scripts/setup
    dest: /usr/local/bin/setup
    owner: root
    group: root
    mode: 0700
  tags:
    - install

- name: Facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0700
  tags:
    - install

- uri:
    url: https://ipinfo.io/ip
    method: GET
    return_content: yes
  register: public_ip
  tags:
    - install

- name: Server remote IP
  template:
    src: templates/server_ip.j2
    dest: /etc/ansible/facts.d/server.fact
    mode: 0644
  when: local == false
  tags:
    - install

- name: Running server script
  template:
    src: templates/ovpn.j2
    dest: /usr/local/bin/ovpn
    mode: 0755
  tags:
    - install

- name: Clients script
  template:
    src: templates/add_client.j2
    dest: /usr/local/bin/addclient
    mode: 0700
  tags:
    - install

- name: Server configuration file
  template:
    src=templates/server.conf.j2
    dest="{{ openvpn_dir }}/server.conf"
  tags:
    - install

